
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BR DASH EXPR NL SH SIGN UN VARbegin : BR DASH VAR exp SH NLexp : SIGN VAR expexp : '
    
_lr_action_items = {'BR':([0,],[2,]),'$end':([1,9,],[0,-1,]),'DASH':([2,],[3,]),'VAR':([3,6,],[4,8,]),'SIGN':([4,8,],[6,6,]),'SH':([4,5,8,10,],[-3,7,-3,-2,]),'NL':([7,],[9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'begin':([0,],[1,]),'exp':([4,8,],[5,10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> begin","S'",1,None,None,None),
  ('begin -> BR DASH VAR exp SH NL','begin',6,'p_begin','parser.py',21),
  ('exp -> SIGN VAR exp','exp',3,'p_expr_rec','parser.py',26),
  ('exp -> <empty>','exp',0,'p_expr_empty','parser.py',33),
]
